apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer  # Docker Desktop'ta bu bize localhost'u açar
  selector:
    app: python-app   # Hangi etiketli podlara trafik gönderecek?
  ports:
    - protocol: TCP
      port: 80        # Dışarıdan (tarayıcıdan) hangi portla gelelim?
      targetPort: 8080 # İçerideki konteyner hangi portu dinliyor?
